import ThemeRegistry from "../lib/ThemeRegistry";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mau carrinho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
